// Generated by CoffeeScript 1.6.2
(function() {
  var app, express, fs, images, io, path, server;

  express = require('express');

  app = express();

  server = require('http').Server(app);

  io = require('socket.io').listen(server);

  path = require('path');

  fs = require('fs');

  images = fs.readdirSync('./public/uploads');

  app.configure(function() {
    app.set('port', process.env.PORT || 3000);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser({
      keepExtensions: true,
      uploadDir: './public/uploads',
      limit: '2mb'
    }));
    app.use(express.methodOverride());
    app.use(app.router);
    return app.use(express["static"](path.join(__dirname, 'public')));
  });

  if ('development' === app.get('env')) {
    app.use(express.errorHandler());
  }

  app.get('/', function(req, res) {
    return res.render('index', {
      "images": images
    });
  });

  app.post('/', function(req, res) {
    var name;

    name = req.files.image.path.substring(15);
    images.unshift(name);
    io.sockets.emit('new image', name);
    console.log('sent event ' + name);
    return res.end();
  });

  server.listen(app.get('port'), function() {
    return console.log('Express server listening on port ' + app.get('port'));
  });

  io.configure(function() {
    io.set("transports", ["xhr-polling"]);
    return io.set("polling duration", 10);
  });

}).call(this);
